### ISSUE TITLE
Swap-Reload-and-Shooting-Controls

### ISSUE THREAD

**Issue by WongIong** [Lorenzo0111/QualityArmory#164]
If the value Swap-Reload-and-Shooting-Controls is true, people cant fire as single-fire when shifting.
also the fully auto would turn to burst mode when you press RMB once. it supposed to be single-fire (maybe?)

**Comment by WongIong** [comment]
https://youtu.be/QjB2w_s3OjI
either you shift or not, it still shots as burst (fully auto).

**Comment by Lorenzo0111** [comment]
Added waiting because issue is really old and could be fixed. Feel free to let me know if persists with last dev build.
