### ISSUE TITLE
Full auto doesnt work with sentinel NPC's

### ISSUE THREAD

**Issue by imDanielll** [Lorenzo0111/QualityArmory#228]
I am currently using QA with sentinel and citizens plugins. It works pretty well, but when equipping an npc with a full auto rifle, it only fires one shot at a time. I want npc's to fire full automatically with an automatic rifle obviously. Any way to change or fix this?

**Comment by Lorenzo0111** [comment]
how are you equipping that item?

**Comment by Lorenzo0111** [comment]
Added waiting because issue is really old and could be fixed. Feel free to let me know if persists with last dev build.
