### ISSUE TITLE
[Bug]: Sentinels Integration Broken

### ISSUE THREAD

**Issue by Ultrajungleboy** [Lorenzo0111/QualityArmory#551]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Sentinel integration is broken across the board
Players don't take damage with armor equipped
The NPC will shoot as fast as sentinel's does update checks regardless of fire rate on any weapon & one shot will be fired
NPC does not reload the gun they shoot like they have infinite ammo
Attack rate ranged or close has no effect on the fire rate it is purely based on the update rate of sentinels

### Expected Behaviour

Player should take damage, guns should work with full auto, and they should also reload

### Plugins

Sentinel, Citizens

### Server Version

1.20.2

### Relevant log output

```shell
No errors in log
```

**Comment by Lorenzo0111** [comment]
Fixed (#573)
