### ISSUE TITLE
[Bug]: residence protect can't work

### ISSUE THREAD

**Issue by minecraft-dripdrop** [Lorenzo0111/QualityArmory#555]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

guns can kill animals in others' residence even if don't have permission

### Expected Behaviour

the gun can't kill animals

### Plugins

Residence

### Server Version

purpur-1.20.1-2035

**Comment by Lorenzo0111** [comment]
What gun are you using?

**Comment by minecraft-dripdrop** [comment]
please test，any guns I made can kill the other people's residence animals

**Comment by Lorenzo0111** [comment]
Only animals or also players?

**Comment by minecraft-dripdrop** [comment]
> Only animals or also players?

animals
