### ISSUE TITLE
[Feature]: why don't you set the right mouse to shoot 

### ISSUE THREAD

**Issue by sanqiuu** [Lorenzo0111/QualityArmory#565]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

New gun

### Description

Left mouse make shoot be single fire ,and shift key let player walk slowly ,why you use this  terrible way

**Comment by Lorenzo0111** [comment]
This is not possible due to minecraft limitations
