### ISSUE TITLE
[Bug]: Automatic guns not using ammo while not crouched

### ISSUE THREAD

**Issue by Seth019-3** [Lorenzo0111/QualityArmory#572]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

Whenever I am not crouched down, any weapon with
`isAutomatic: true`
appears to not consume ammo.

However, when I go to the configs and set isAutomatic to false this issue just disappears.
[Example Video](https://youtu.be/koNGhjH55Hk)
(Above is a youtube redirect)

If it is relevant whatsoever I am using `Swap-Reload-and-Shooting-Controls: true` and the plugin version is 2.0.11

### Expected Behaviour

I expected that the plugin would consume a shot each shot while firing full auto without me having to convert the gun to, effectively, a semi-automatic state.

### Plugins

Nova, AntiHealthIndicator, AuctionHouse, AureliumSkills, BaritoneRemover, BetterPortals, BlueMap, BlueMap-Towny, BlueMapPlayerControl, Brewery, Chunky, ChunkyBorder, CoreProtect, DivinityEconomy, EzChestShop, FlagsH, FlagWar, FoxAddition, GrimAC, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LevelledMobs, LibertyBans, LuckPerms, MobsToEggs, NBTAPI, Orebfuscator, ProtocolLib, QualityArmory, Towny, TownyChat, TownyCultures, TownyMenus, TownyProvinces, TownyResources, vane-admin, vane-bedtime, vane-core, vane-portals, vane-trifles, Vault, voicechat

### Server Version

This server is running Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87) You are running the latest version Previous version: git-Paper-422 (MC: 1.20.4)

**Comment by Lorenzo0111** [comment]
Could you try with this? https://ci.codemc.io/job/ZombieStriker/job/QualityArmory/lastSuccessfulBuild/artifact/target/QualityArmory.jar

**Comment by Seth019-3** [comment]
That seems to have fixed the issue, thanks!
