### ISSUE TITLE
[Bug]: Firearms deleted by Offhand slot

### ISSUE THREAD

**Issue by Oonezumikamisama** [Lorenzo0111/QualityArmory#574]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

While in Creative Mode, placing firearms in the oddhand slot causes them to be removed from the inventory. When closing the inventory, only the last firearm removed is returned to the player's inventory, with the rest seemingly deleted.

### Expected Behaviour

The player should be unable to place firearms in the offhand slot, bringing behavior in line with Survival Mode.

### Plugins

QualityArmory

### Server Version

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7) You are running the latest version

**Comment by Lorenzo0111** [comment]
Could you send a video of you reproducing the issue?
