### ISSUE TITLE
[Feature]: 1.20.5 / 6 support?

### ISSUE THREAD

**Issue by RedstoneGyerek** [Lorenzo0111/QualityArmory#576]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

hi
im just curious if youre planning to make a relase that supports 1.20.5 or 1.20.6
i have a server that uses crackshot and i was planning to update the server, and noticed thats not maintained anymore, so i decided to try this plugin out
i tested it in a 1.20.6 server and it kinda worked, but kinda didnt at the same time
i guess this is because of the new item components, but the guns were just crossbows
(the models and crafting gui all worked, only the gun functionality and /qa give command didnt work)

**Comment by Lorenzo0111** [comment]
Added with 3f33a1430dfe9c905b3755c66cd21198dd74c791
