### ISSUE TITLE
[Feature]: Add parameter to select player to send the Resource pack to.

### ISSUE THREAD

**Issue by Relaxing9** [Lorenzo0111/QualityArmory#582]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

Be able to add a name to the end of the `/qa sendResourcepack` command, so it can be either `/qa [playerName] sendResourcepack` or `/qa sendResourcepack [playerName]`. My use case is not to have people have too many commands, but be able to step on a Command Block (Also have `playerName` work with `@p`) and have that autoran for you. Also of note is even if you are on the whitelist to get the resourcepack you don't automatically get it, only when you run the command.

**Comment by Lorenzo0111** [comment]
If you have the `qualityarmory.sendresourcepack.other` permission you are already able to use the `/qa sendResourcepack <player>` command.
Remember that selectors (`@p`, `@s` etc) are not supported by plugins by default so you should use some external plugin such as [PsudoCommands](https://www.spigotmc.org/resources/83535/)

**Comment by Relaxing9** [comment]
I managed to get it to work with essentials sudo * qa sendResourcepack. The gimmick was for players to step on a pressure plate to trigger this command, not to rely on someone running it for someone.
