### ISSUE TITLE
[Bug]: No items or weapons in QualityArmory are working in MC 1.21.1, huge errors thrown

### ISSUE THREAD

**Issue by TuckerAndrews3** [Lorenzo0111/QualityArmory#587]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

No weapons or items in Quality Armory do anything.

### Expected Behaviour

The items should work as intended.

### Plugins

Quality Armory

### Server Version

1.21.1

### Relevant log output

```shell
https://pastebin.com/acicYnKC
```

**Comment by Lorenzo0111** [comment]
Fixed with 27e0fe97139525cd1279ba8ea568007c10e7647e
