### ISSUE TITLE
[Feature]: blocks don't regenerate

### ISSUE THREAD

**Issue by BattleMN** [Lorenzo0111/QualityArmory#589]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

The blocks do not regenerate when broken by any type of explosion from weapons such as RPG, Fatman, among others.. How can I solve it?
![image](https://github.com/user-attachments/assets/4b0158f9-465c-4545-be86-f627592bff52)
![image](https://github.com/user-attachments/assets/f0fef9e9-8e32-4c9c-b892-f4042a53d001)

**Comment by Lorenzo0111** [comment]
Already explained on discord: The guns you listed are related to explosions and works as a tnt, this means we can't regenerate the blocks for them
