### ISSUE TITLE
[Feature]: please edit readme

### ISSUE THREAD

**Issue by Monster2408** [Lorenzo0111/QualityArmory#592]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

Please add `<scope>provided</scope>` as the event will not fire properly without it.
This issue is discussed in [here](https://github.com/Lorenzo0111/QualityArmory/issues/528).

```xml
<dependency>
    <groupId>me.zombie_striker</groupId>
    <artifactId>QualityArmory</artifactId>
    <version>VERSION</version>
</dependency>
```
to
```xml
<dependency>
    <groupId>me.zombie_striker</groupId>
    <artifactId>QualityArmory</artifactId>
    <version>VERSION</version>
    <scope>provided</scope>
</dependency>
```

**Comment by Lorenzo0111** [comment]
Well that's normal. If you bundle the jar in yours it won't work. I'll add it to make it more clear.
