### ISSUE TITLE
[Feature]: add Bedrock support for the resource pack

### ISSUE THREAD

**Issue by 6vers** [Lorenzo0111/QualityArmory#593]
### Confirmations

- [X] There isn't any other PR or issue regarding this.
- [X] This feature does not exist in the latest version.

### What is your request about?

Other

### Description

add Bedrock support for the Resource pack currently bedrock players joining trough geyser can't see the weapons in anyway.
Would be very if you could add support for it so that bedrock players joining trough geyser could also somehow get the resource pack.

**Comment by Lorenzo0111** [comment]
This won't be done. I have no experience with bedrock resourcepacks and I'm so unable to do that. There are many resources online that explains how to convert it yourself but I'm not able to provide an official way to do so
