### ISSUE TITLE
[Bug]: Gun visual bug only with ProtocolLib

### ISSUE THREAD

**Issue by DanielDark1** [Lorenzo0111/QualityArmory#603]
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

After aiming the gun has the wrong model making it appear in off hand.
https://imgur.com/a/Y06FvxG
This only happens when there are 2 or more online players and ProtocolLib is installed.

### Expected Behaviour

The plugin should switch to the right hand model after aiming with the weapon.

### Plugins

QualityArmory, ProtocolLib

### Server Version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)

**Comment by Lorenzo0111** [comment]
Should be fixed in last dev build. Please try again or open the issue again if it persists
